environment_variables:
  OPENROUTER_API_KEY: "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"

litellm_settings:
  default_provider: openrouter
  api_base: "https://openrouter.ai/api/v1"
  model_aliases:
    meta-llama/llama-3.1-70b-instruct: openrouter/meta-llama/llama-3.1-70b-instruct
    meta-llama/llama-3.1-8b-instruct: openrouter/meta-llama/llama-3.1-8b-instruct
